import type { CSSProperties } from "react";

export const fileUploadStyles: Record<string, CSSProperties> = {
  container: {
    minHeight: "100vh",
    background: "#f4f6f9",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  content: {
    width: "100%",
    maxWidth: "860px",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    alignItems: "center",
    textAlign: "center",
  },
  title: {
    margin: 0,
    fontSize: "56px",
    fontWeight: 900,
    color: "#0d1f3c",
    letterSpacing: "-0.6px",
  },
  subTitle: {
    margin: 0,
    fontSize: "18px",
    color: "#4a5568",
    lineHeight: 1.6,
    maxWidth: "720px",
  },
  dropCard: {
    width: "100%",
    maxWidth: "780px",
    marginTop: "18px",
    borderRadius: "16px",
    backgroundColor: "#ffffff",
    border: "1px solid #e2e8f0",
    boxShadow: "0 8px 30px rgba(0,0,0,0.08)",
    padding: "18px",
  },
  dropZone: {
    borderRadius: "14px",
    border: "2px dashed #cbd5e0",
    padding: "22px 18px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8fafc",
    textAlign: "center",
  },
  dropZoneActive: {
    border: "2px dashed #1f4e8c",
    backgroundColor: "rgba(31, 78, 140, 0.05)",
  },
  bigBtn: {
    width: "100%",
    height: "52px",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    backgroundColor: "#1f4e8c",
    color: "#ffffff",
    fontWeight: 800,
    letterSpacing: "0.5px",
    fontSize: "14px",
    boxShadow: "0 10px 26px rgba(31, 78, 140, 0.25)",
  },
  helper: {
    fontSize: "13px",
    color: "#718096",
  },
  note: {
    marginTop: "10px",
    fontSize: "12px",
    color: "#a0aec0",
    lineHeight: 1.5,
  },
  fileList: {
    marginTop: "14px",
    borderRadius: "12px",
    border: "1px solid #e2e8f0",
    backgroundColor: "#f8fafc",
    overflow: "hidden",
  },
  fileRow: {
    padding: "12px 12px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #e2e8f0",
    color: "#2d3748",
    fontSize: "13px",
  },
  fileRowLast: {
    borderBottom: "none",
  },
  fileMeta: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  fileName: {
    fontWeight: 800,
  },
  fileSize: {
    fontSize: "12px",
    color: "#718096",
  },
  removeBtn: {
    border: "1px solid #e2e8f0",
    backgroundColor: "transparent",
    color: "#4a5568",
    borderRadius: "10px",
    height: "32px",
    padding: "0 10px",
    cursor: "pointer",
    fontWeight: 700,
  },
  actionRow: {
    marginTop: "12px",
    display: "flex",
    gap: "10px",
  },
  secondaryBtn: {
    height: "44px",
    padding: "0 14px",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    backgroundColor: "#ffffff",
    color: "#4a5568",
    cursor: "pointer",
    fontWeight: 800,
  },
};