export const scanResultStyles = {
  page: {
    minHeight: "100vh",
    background: "#f4f6f9",
    color: "#0f172a",
    padding: "40px 52px",
    boxSizing: "border-box" as const,
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Noto Sans KR', Arial, sans-serif",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 20,
    marginBottom: 24,
  },
  title: {
    margin: 0,
    fontSize: 34,
    fontWeight: 900,
    letterSpacing: 0,
  },
  subtitle: {
    margin: "8px 0 0",
    color: "#64748b",
    fontSize: 15,
    lineHeight: 1.6,
  },
  button: {
    height: 42,
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    color: "#334155",
    borderRadius: 8,
    padding: "0 14px",
    fontWeight: 800,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
  },
  primaryButton: {
    height: 38,
    border: "1px solid #1d4ed8",
    background: "#2563eb",
    color: "#ffffff",
    borderRadius: 8,
    padding: "0 12px",
    fontWeight: 900,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
  },
  disabledButton: {
    opacity: 0.55,
    cursor: "not-allowed",
  },
  reportHero: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.4fr) minmax(320px, 0.8fr)",
    gap: 18,
    marginBottom: 18,
  },
  riskCardBase: {
    borderRadius: 8,
    padding: "22px 24px",
    display: "flex",
    gap: 16,
    alignItems: "flex-start",
  },
  riskIconBase: {
    width: 44,
    height: 44,
    borderRadius: 8,
    background: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  riskLabelBase: {
    display: "inline-flex",
    alignItems: "center",
    height: 24,
    padding: "0 9px",
    borderRadius: 999,
    background: "#ffffff",
    fontSize: 12,
    fontWeight: 900,
    marginBottom: 9,
  },
  riskTitleBase: {
    margin: 0,
    fontSize: 22,
    fontWeight: 900,
    letterSpacing: 0,
  },
  riskText: {
    margin: "8px 0 0",
    color: "#334155",
    fontSize: 14,
    lineHeight: 1.6,
  },
  insightPanel: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "18px 20px",
  },
  insightTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 900,
  },
  ratioBar: {
    height: 10,
    borderRadius: 999,
    background: "#e2e8f0",
    overflow: "hidden",
    marginTop: 14,
  },
  ratioFillBase: {
    height: "100%",
  },
  insightLine: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 12,
    color: "#475569",
    fontSize: 13,
    lineHeight: 1.5,
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, minmax(120px, 1fr))",
    gap: 12,
    marginBottom: 22,
  },
  summary: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "16px 18px",
    minHeight: 92,
    boxSizing: "border-box" as const,
  },
  summaryLabel: {
    fontSize: 12,
    fontWeight: 800,
    color: "#64748b",
  },
  summaryValue: {
    marginTop: 8,
    fontSize: 30,
    fontWeight: 900,
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "360px minmax(0, 1fr)",
    gap: 18,
    alignItems: "start",
  },
  panel: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    overflow: "hidden",
  },
  panelTitle: {
    margin: 0,
    padding: "16px 18px",
    borderBottom: "1px solid #e2e8f0",
    fontSize: 16,
    fontWeight: 900,
  },
  fixItem: {
    padding: "14px 18px",
    borderBottom: "1px solid #f1f5f9",
  },
  packageType: {
    display: "inline-flex",
    alignItems: "center",
    height: 22,
    marginTop: 8,
    padding: "0 8px",
    borderRadius: 999,
    background: "#eef2ff",
    color: "#3730a3",
    fontSize: 12,
    fontWeight: 900,
  },
  guideBox: {
    marginTop: 10,
    padding: "10px 12px",
    borderRadius: 8,
    background: "#f8fafc",
    color: "#334155",
    fontSize: 12,
    lineHeight: 1.5,
    wordBreak: "break-word" as const,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: 13,
  },
  tableWrap: {
    maxHeight: 360,
    overflow: "auto",
    borderTop: "1px solid #e2e8f0",
  },
  fixPlanGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 14,
    padding: 18,
  },
  fixPlanColumn: {
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    overflow: "hidden",
    background: "#ffffff",
  },
  fixPlanColumnHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    padding: "13px 14px",
    background: "#f8fafc",
    borderBottom: "1px solid #e2e8f0",
    fontWeight: 900,
  },
  planItem: {
    padding: "13px 14px",
    borderBottom: "1px solid #eef2f7",
  },
  planMeta: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 8,
    marginTop: 8,
    color: "#64748b",
    fontSize: 12,
  },
  smallPill: {
    display: "inline-flex",
    alignItems: "center",
    height: 22,
    padding: "0 8px",
    borderRadius: 999,
    background: "#eef2ff",
    color: "#3730a3",
    fontSize: 12,
    fontWeight: 900,
  },
  tableHeaderText: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "16px 18px",
    borderBottom: "1px solid #e2e8f0",
  },
  sectionHeading: {
    margin: 0,
    fontSize: 16,
    fontWeight: 900,
  },
  sectionDescription: {
    margin: "4px 0 0",
    color: "#64748b",
    fontSize: 13,
    lineHeight: 1.5,
  },
  countPill: {
    display: "inline-flex",
    alignItems: "center",
    height: 30,
    padding: "0 10px",
    borderRadius: 999,
    background: "#f1f5f9",
    color: "#334155",
    fontSize: 12,
    fontWeight: 900,
    whiteSpace: "nowrap" as const,
  },
  th: {
    textAlign: "left" as const,
    background: "#f8fafc",
    color: "#475569",
    padding: "12px 14px",
    borderBottom: "1px solid #e2e8f0",
    fontWeight: 900,
  },
  td: {
    padding: "12px 14px",
    borderBottom: "1px solid #eef2f7",
    verticalAlign: "top" as const,
  },
  componentName: {
    maxWidth: 520,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  mono: {
    fontFamily:
      "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', monospace",
  },
};

export type ScanResultStyles = typeof scanResultStyles;
